### ISSUE TITLE
Literal "table1" erroneously recognised as keyword Table. 

### ISSUE THREAD

**Issue by SUMUKHA-PK** [tomarrell/lbadd#103]
**Describe the bug**

The keyword table is being recognised by the scanner in the case of the word `table1` instead of a literal `table1`

**To Reproduce**

Test for the keyword `table1`

**Expected behavior**
Literal `table1` instead of KeywordTable

**Comment by TimSatke** [comment]
Does this happen for every literal that starts with a keyword?
such as `selectx` or `joinTable`?

**Comment by SUMUKHA-PK** [comment]
Yes it does. `selectTable` is not a literal.

**Comment by TimSatke** [comment]
Fixed as of d9337b73dbd5001b21cd7b1f8f00c378e3621a28
