### ISSUE TITLE
staticcheck Failed

### ISSUE THREAD

**Issue by TimSatke** [tomarrell/lbadd#13]
## ⚠ staticcheck Failed
```
btree.go:187:3: empty branch (SA9003)
btree_test.go:291:3: field order is unused (U1000)
executor.go:16:6: type record is unused (U1000)
executor.go:19:6: type row is unused (U1000)
executor.go:23:2: field columns is unused (U1000)
executor.go:24:2: field rows is unused (U1000)
executor.go:25:2: field rowsAffected is unused (U1000)
query.go:6:2: field conditions is unused (U1000)
query.go:7:2: field updates is unused (U1000)
query.go:8:2: field inserts is unused (U1000)
query.go:72:6: type condition is unused (U1000)
```

[Checks Document](https://staticcheck.io/docs/checks)

_Originally posted by @github-actions in https://github.com/tomarrell/lbadd/pull/10#issuecomment-570262390_

**Comment by tomarrell** [comment]
Solved in 5f1ac8bc630c9ec8cc817434f48ea986629f1cb9

**Comment by TimSatke** [comment]
@tomarrell can you re-enable the github action step?

**Comment by tomarrell** [comment]
Oh right apologies. I misinterpreted this. Will leave it open until we're making use of these things and can re-enable it.
