### ISSUE TITLE
parser: parseExpr calls from other statements is broken 

### ISSUE THREAD

**Issue by SUMUKHA-PK** [tomarrell/lbadd#153]
**Describe the bug**
After visiting a token of a possible `expr`, there is no function to parse expr from that point.

**To Reproduce**
See #151 

Adding a helper function that takes in the first element of a possible expr and returns the parsed expr is needed.

**Comment by TimSatke** [comment]
Is this a duplicate of #151 ? What is this issue good for? Is this the actual issue causing #151 ?

**Comment by SUMUKHA-PK** [comment]
This is a superset of #151, I'm just covering all bases to make sure more bugs dont turn up in other places.

**Comment by SUMUKHA-PK** [comment]
Closing until any problem comes up.
