### ISSUE TITLE
parser: invalid input VALUES()

### ISSUE THREAD

**Issue by TimSatke** [tomarrell/lbadd#158]
**Describe the bug**
When parsing `VALUES()`, this results in an invalid ast.
The parenthesized expressions have 1 element, and that is `nil`.
However, this must not be parsed, because it is not allowed by the grammar.

**To Reproduce**
Parse `VALUES()`.

**Expected behavior**
A parser error.

**Additional context**
Found by our fuzzer.

**Comment by SUMUKHA-PK** [comment]
Closed in #163
