### ISSUE TITLE
found invalid input while fuzzing

### ISSUE THREAD

**Issue by TimSatke** [tomarrell/lbadd#161]
**Describe the bug**
`SELECT 0*FROM y` causes a panic in `compileExpr`.
However, this looks like it shouldn't have passed the parser.

**Comment by TimSatke** [comment]
@SUMUKHA-PK is this a parser issue?

**Comment by SUMUKHA-PK** [comment]
Yes it is.

I think I know what the problem is too.
Might be quite a small fix.

I shouldn't allow blank expressions in the end while parsing `expr * expr` type stmts.
