### ISSUE TITLE
parser: parseExpr4 runs in infinite recursion

### ISSUE THREAD

**Issue by TimSatke** [tomarrell/lbadd#210]
**Describe the bug**
Fuzzing fails.

**To Reproduce**
Parse any of the attached crasher files.

Crash files are attached
[Archive.zip](https://github.com/tomarrell/lbadd/files/4947340/Archive.zip)
[Archive 2.zip](https://github.com/tomarrell/lbadd/files/4947346/Archive.2.zip)
[Archive 3.zip](https://github.com/tomarrell/lbadd/files/4947348/Archive.3.zip)
[Archive 4.zip](https://github.com/tomarrell/lbadd/files/4947349/Archive.4.zip)

**Expected behavior**
No crash

**Comment by SUMUKHA-PK** [comment]
Turned out to be not the fault of `parseExpr4` but issues in scanner not being able to support some statements.
