### ISSUE TITLE
docs: create document with component explanation

### ISSUE THREAD

**Issue by tomarrell** [tomarrell/lbadd#22]
It's been pointed out that it's not entirely clear what the purpose of each component in the database is.

Therefore we should have a document which takes a high level approach to describing the function of each component.

**Comment by SUMUKHA-PK** [comment]
This seems to be quite vague, we can probably have individual issues to individual components so that they can be resolved. (This might be a permanent existing issue otherwise)
Thoughts?

**Comment by TimSatke** [comment]
sounds good, already did that for many things, seems to work quite well
