### ISSUE TITLE
internal/parser: implement parser for SQL-2016 standard

### ISSUE THREAD

**Issue by tomarrell** [tomarrell/lbadd#4]
Currently the parser supports only extremely basic SELECT statements. 

We need to add support for SELECT, INSERT, CREATE, UPDATE, DELETE

**Comment by TimSatke** [comment]
Would like to do this. Could you add more info and a spec that I can implement?

**Comment by tomarrell** [comment]
Great to hear! 

Absolutely. The parser here is based on the implementation by @marianogappa over at https://github.com/marianogappa/sqlparser

The idea is to use that as a reference for the simple commands listed above. 

Ultimately we need a structure out that contains all relevant information neatly laid out for the code generation step. 

A good start would be something along the lines of Mariano’s `query.Query` struct. 

Let me know if that’s enough to get you started!

**Comment by tomarrell** [comment]
Also re: a separate package. Sure, sounds like a good idea 👍

**Comment by TimSatke** [comment]
This sounds like a really interesting project with a lot of roundtrips through all imaginable components... I would like to keep contributing... mind adding me to the repo?

**Comment by tomarrell** [comment]
Sure thing. I've added you as a collaborator. Feel free to work on whatever you feel like. I'm currently in progress with the btree implementation.

**Comment by TimSatke** [comment]
Besides that, are you interested in supporting a specific SQL version?

https://modern-sql.com/de/standard
-> https://jakewheat.github.io/sql-overview/sql-2008-foundation-grammar.html

This looks like something I could implement a parser for... not everything has to be supported by a runtime or similar, but you could already parse it if support is desired in the future.

**Comment by TimSatke** [comment]
Are you sure you did add me? Do I have write access enabled?

**Comment by tomarrell** [comment]
You should have received an email with an invitation link which you can accept. 

That sql 2008 foundation grammar you linked looks sensible. Would be happy to move forward with that.

**Comment by TimSatke** [comment]
Alright, on it. Will develop on separate branch.

**Comment by TimSatke** [comment]
Decided to switch to SQL-2016, since the differences do not seem too big at first glance.
That ok?

**Comment by tomarrell** [comment]
Sounds good!

**Comment by TimSatke** [comment]
SQL-2016 is too heavyweight, we decided to go for a variant of `Sqlite`. See #34
