### ISSUE TITLE
Purpose of this Package? Does it provide any performance improvement against sqlite, or similar?

### ISSUE THREAD

**Issue by rebootcode** [tomarrell/lbadd#6]
Purpose of this Package? Does it provide any performance improvement against sqlite, or similar?

**Comment by tomarrell** [comment]
The purpose is mainly for people who are interested in learning more about the inner workings of distributed databases.

As mentioned in the readme:
> The goal of this project is to build a database from scratch which is well documented, fully tested, and easy to understand.
