### ISSUE TITLE
slack channel

### ISSUE THREAD

**Issue by TimSatke** [tomarrell/lbadd#7]
Is there a slack channel or similar that facilitates communication?

**Comment by tomarrell** [comment]
I’ll set one up now.

**Comment by tomarrell** [comment]
Here's the invite link.

https://join.slack.com/t/lbadd/shared_invite/enQtODgzMDM5ODM4MDY5LTkzMzQ0ZjY0NDdjYzFiZDU0ZjNiYjQyMmZlMzRlZDU0MGJhNjgxZTA3MTA1N2M2YjM5Y2ZlNmUwNDc2MzgxZjg

**Comment by TimSatke** [comment]
what about a channel on the gopher's slack?
https://slack.com/share/IS711LXRB/7pFqNjAnnXr9f1huaeE3upF0/enQtODkxMDM1NzExODYxLTQ3NDc4MmM0NTZkZjRhNjAxOTNlY2NkYjNkOWI2OThjNDUyY2Q3OWJjODc4NzY3NGQzZWJhN2U3YTQxMzE0NjU

**Comment by TimSatke** [comment]
@tomarrell does this slack link also need an update?

**Comment by tomarrell** [comment]
Ah yes, I'll update the comment here just to prevent confusion.

**Comment by tomarrell** [comment]
Done.
